services:
    k7_twig_spreadsheet.add_request_formats_listener:
        class: K7\TwigSpreadsheetBundle\EventListener\AddRequestFormatsListener
        tags:
            - { name: kernel.event_subscriber }

    k7_twig_spreadsheet.twig_spreadsheet_extension:
        class: K7\TwigSpreadsheetBundle\Twig\TwigSpreadsheetExtension
        public: true
        arguments: [ null ] # config placeholder
        tags:
            - { name: twig.extension }
